version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=user-app
      - MYSQL_DATABASE=users-app
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d
    command: '--default-authentication-plugin=mysql_native_password'
  api:
    image: users-api:latest
    container_name: users-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USERNAME=user-app
      - DATABASE_NAME=users-app
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=1234
    depends_on:
      - db
