version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=P@sssw0d!
      - MYSQL_PASSWORD=P@sssw0d!
      - MYSQL_USER=user-app
      - MYSQL_DATABASE=userapp
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d
    command: '--default-authentication-plugin=mysql_native_password'
  api:
    image: users-api:latest
    container_name: users-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USERNAME=userapp
      - DATABASE_NAME=userapp
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=P@sssw0d!
    depends_on:
      - db
